name: Node App CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Lint and Test
        run: |
          npm run lint
          npm test

      - name: Build Docker Image
        run: docker build -t my-node-app:latest .

      - name: Run Docker Container
        run: |
          docker rm -f my-node-app || true
          docker run -d -p 3000:3000 --name my-node-app my-node-app:latest
